# Generated by Django 5.0.2 on 2024-03-05 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "description",
                    models.CharField(
                        help_text="Please provide a detailed description of the item being auctioned.",
                        max_length=1024,
                    ),
                ),
                (
                    "starting_bid",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The minimum amount that a bidder can offer for this item.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
            ],
        ),
    ]
