# Generated by Django 5.0.2 on 2024-03-06 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_listing_watchlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="watchlist",
        ),
    ]
