# Generated by Django 5.0.2 on 2024-03-06 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_remove_listing_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="watchlist", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
