# Generated by Django 5.0.2 on 2024-03-06 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_listing_watchlist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="watchlist",
            new_name="users",
        ),
    ]
