# Generated by Django 5.0.2 on 2024-03-06 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_rename_watchlist_listing_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="listings", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
