# Generated by Django 5.0.2 on 2024-03-08 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="bids",
            field=models.ManyToManyField(
                blank=True, related_name="listing_bids", to="auctions.bid"
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bid_listings",
                to="auctions.listing",
            ),
        ),
    ]
