# Generated by Django 5.0.2 on 2024-03-09 18:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_listing_bids_alter_bid_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
