# Generated by Django 5.0.2 on 2024-03-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_listing_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="num_bids",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
