# Generated by Django 5.0.2 on 2024-03-12 16:21

from django.db import migrations, models

def set_active_to_true(apps, schema_editor):
    Listing = apps.get_model('auctions', 'Listing')
    Listing.objects.all().update(active=True)


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0014_listing_active"),
    ]

    operations = [migrations.RunPython(set_active_to_true),]
