# Generated by Django 5.0.2 on 2024-03-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0017_alter_comment_created_by_alter_comment_listing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="listings",
            field=models.ManyToManyField(
                blank=True, related_name="categories", to="auctions.listing"
            ),
        ),
    ]
