# Generated by Django 5.0.2 on 2024-03-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0018_alter_category_listings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="listings",
        ),
        migrations.AddField(
            model_name="listing",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="category_listings", to="auctions.category"
            ),
        ),
    ]
