# Generated by Django 5.0.2 on 2024-03-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0019_remove_category_listings_listing_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="listing_images/"),
        ),
    ]
